name: admin_web_ste
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.27.1
  firebase_storage: ^11.7.0
  flutter:
    sdk: flutter
  get: 4.6.5
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
