// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2ZL-IdeiHulplNu1de-avhhzEWaBplo',
    appId: '1:173578785882:web:273675e9d80d27e9023463',
    messagingSenderId: '173578785882',
    projectId: 'pendaftaran-kedai',
    authDomain: 'pendaftaran-kedai.firebaseapp.com',
    databaseURL:
        'https://pendaftaran-kedai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pendaftaran-kedai.appspot.com',
    measurementId: 'G-RB3S8G741Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTaebgzmUaOFSCeCV0ZgGST-mTXoCj1I',
    appId: '1:173578785882:android:e41c8531f6d2ad76023463',
    messagingSenderId: '173578785882',
    projectId: 'pendaftaran-kedai',
    databaseURL:
        'https://pendaftaran-kedai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pendaftaran-kedai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_HkYPshzRjos0eP08B8x_kYtMHdaGLC0',
    appId: '1:173578785882:ios:5309114aa8318595023463',
    messagingSenderId: '173578785882',
    projectId: 'pendaftaran-kedai',
    databaseURL:
        'https://pendaftaran-kedai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pendaftaran-kedai.appspot.com',
    androidClientId:
        '173578785882-0mmr9ibo580bduhhj1c59cnpqphff40f.apps.googleusercontent.com',
    iosClientId:
        '173578785882-cic71cn4i6nsfkbhr1deaseos8nv6ip5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWebSte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_HkYPshzRjos0eP08B8x_kYtMHdaGLC0',
    appId: '1:173578785882:ios:3620b000bd004325023463',
    messagingSenderId: '173578785882',
    projectId: 'pendaftaran-kedai',
    databaseURL:
        'https://pendaftaran-kedai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pendaftaran-kedai.appspot.com',
    androidClientId:
        '173578785882-0mmr9ibo580bduhhj1c59cnpqphff40f.apps.googleusercontent.com',
    iosClientId:
        '173578785882-1ootgp4gvv4850256smtd86oubr9ape8.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWebSte.RunnerTests',
  );
}
